---
- name: Configure workstation
  hosts: localhost
  become: true
  pre_tasks:
    - name: Gather service facts
      ansible.builtin.service_facts:

    - name: Disable and stop PackageKit to release zypper lock
      ansible.builtin.service:
        name: packagekit
        state: stopped
        enabled: false
      when: "'packagekit.service' in ansible_facts.services"
  roles:
    - role: packages
      tags: packages
    - role: dev_tools
      tags: dev_tools
    - role: containers
      tags: containers
    - role: kubernetes
      tags: kubernetes
    - role: browsers
      tags: browsers

- name: Deploy dotfiles
  hosts: localhost
  become: false
  roles:
    - role: fonts
      tags: fonts
    - role: dotfiles
      tags: dotfiles
    - role: ssh_keys
      tags: ssh_keys
    - role: nvm
      tags: nvm
    - role: powerline
      tags: powerline
