---
- name: Prepare
  hosts: all
  become: false
  gather_facts: false
  tasks:
    - name: Install sudo, python3, curl, and bash
      ansible.builtin.raw: zypper --non-interactive install sudo python3 curl bash gawk
      changed_when: false
