---
- name: Add Kubernetes zypper repository
  community.general.zypper_repository:
    name: "{{ kubernetes_kubectl_repo_name }}"
    repo: "{{ kubernetes_kubectl_repo }}"
    auto_import_keys: true
    state: present

- name: Install kubectl
  community.general.zypper:
    name: kubectl
    state: present

- name: Install minikube binary
  ansible.builtin.get_url:
    url: "{{ kubernetes_minikube_url }}"
    dest: "{{ kubernetes_minikube_dest }}"
    mode: "0755"
