---
- name: Import Brave browser GPG key
  ansible.builtin.rpm_key:
    key: "{{ browsers_brave_gpg_key }}"
    state: present

- name: Add Brave browser repository
  community.general.zypper_repository:
    repo: "{{ browsers_brave_repo }}"
    state: present

- name: Install browsers and mail client
  community.general.zypper:
    name: "{{ browsers_packages }}"
    state: present
