---
nvm_version: v0.40.4
nvm_install_script: "https://raw.githubusercontent.com/nvm-sh/nvm/{{ nvm_version }}/install.sh"
nvm_dir: "{{ ansible_facts['env']['HOME'] }}/.config/nvm"
nvm_node_version: "24.14.1"
